this is just a test file not used for production, but may be used for devlopment

FROM node:22.22.2

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]